// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlb2UlFyMwF0afqhy9GGj57pbvhIEUa5g',
    appId: '1:979945042721:web:d70088348de37bb3cec460',
    messagingSenderId: '979945042721',
    projectId: 'dentalscan-pro',
    authDomain: 'dentalscan-pro.firebaseapp.com',
    storageBucket: 'dentalscan-pro.appspot.com',
    measurementId: 'G-ZX90VG1178',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRZ8EWSA98Db7tkKxomtatS2gU5anC0ZU',
    appId: '1:979945042721:android:a0885a5eccd81998cec460',
    messagingSenderId: '979945042721',
    projectId: 'dentalscan-pro',
    storageBucket: 'dentalscan-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhdWSwg7v8sb6wNGAstsPT-I2iKi0ztQU',
    appId: '1:979945042721:ios:397641302d19c10acec460',
    messagingSenderId: '979945042721',
    projectId: 'dentalscan-pro',
    storageBucket: 'dentalscan-pro.appspot.com',
    iosBundleId: 'com.example.dentalscanpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhdWSwg7v8sb6wNGAstsPT-I2iKi0ztQU',
    appId: '1:979945042721:ios:397641302d19c10acec460',
    messagingSenderId: '979945042721',
    projectId: 'dentalscan-pro',
    storageBucket: 'dentalscan-pro.appspot.com',
    iosBundleId: 'com.example.dentalscanpro',
  );
}
